- name: Install Nginx and configure proxy
  hosts: web
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Generate self-signed SSL certificate
      command: "sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/conf.d/selfsigned.key -out /etc/nginx/conf.d/selfsigned.crt"
      args:
        creates: /etc/nginx/conf.d/selfsigned.crt

    - name: Configure proxy.conf
      template:
        src: proxy.conf.j2
        dest: /etc/nginx/conf.d/proxy.conf
        owner: root
        group: root
        mode: 0644

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
